[package]
name = "notes-builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11.5"
eyre = "0.6.12"
log = "0.4.22"
markdown = "1.0.0-alpha.20"
walkdir = "2.5.0"
